#!/usr/bin/env ruby -w
# encoding: UTF-8
require_relative '../SCRF/加载'
require_relative '代码/加载'
$方法数组 = [:move, :create, :addtag, :addtag_above, :addtag_all, :addtag_below, 
:addtag_closest, :addtag_enclosed, :addtag_overlapping, :addtag_withtag, :bbox, 
:itembind, :itembind_append, :itembind_remove, :itembindinfo, :canvasx, :canvasy, 
:canvas_x, :canvas_y, :coords, :dchars, :delete, :remove, :dtag, :deltag, :find, 
:find_above, :find_all, :find_below, :find_closest, :find_enclosed, :find_overlapping, 
:find_withtag, :itemfocus, :gettags, :icursor, :imove, :i_move, :index, :insert, 
:lower, :moveto, :move_to, :postscript, :raise, :rchars, :replace_chars, 
:replace_coords, :scale, :scan_mark, :scan_dragto, :select, :select_adjust, 
:select_clear, :select_from, :select_item, :select_to, :itemtype, :create_itemobj_from_id, 
:yscrollcommand, :yview, :yview_moveto, :yview_scroll, :yscrollbar, :xscrollcommand, 
:xview, :xview_moveto, :xview_scroll, :xscrollbar, :itemcget_tkstring, :itemcget, 
:itemcget_strict, :__check_available_itemconfigure_options, :itemconfigure, 
:itemconfiginfo, :__current_itemconfiginfo, :current_itemconfiginfo, 
:__conv_item_keyonly_opts, :itemconfig_hash_kv, :tagfont_configinfo, 
:tagfontobj, :tagfont_configure, :latintagfont_configure, :asciitagfont_configure, 
:kanjitagfont_configure, :tagfont_copy, :latintagfont_copy, :asciitagfont_copy, 
:kanjifont_copy, :inspect, :exist?, :subcommand, :bind_class, :database_classname, 
:database_class, :pack, :pack_in, :pack_forget, :unpack, :pack_config, :pack_configure, 
:pack_info, :pack_propagate, :pack_slaves, :grid, :grid_in, :grid_anchor, :grid_forget, 
:ungrid, :grid_bbox, :grid_config, :grid_configure, :grid_columnconfig, :grid_columnconfigure, 
:grid_rowconfig, :grid_rowconfigure, :grid_columnconfiginfo, :grid_rowconfiginfo, :grid_column, 
:grid_row, :grid_info, :grid_location, :grid_propagate, :grid_remove, :grid_size, :grid_slaves, 
:place, :place_in, :place_forget, :unplace, :place_config, :place_configure, :place_configinfo, 
:place_info, :place_slaves, :set_focus, :focus, :grab, :grab_current, :current_grab, 
:grab_release, :release_grab, :grab_set, :set_grab, :grab_set_global, :set_global_grab, 
:grab_status, :lower_window, :raise_window, :command, :colormodel, :caret, :destroy, 
:wait_visibility, :eventloop_wait_visibility, :thread_wait_visibility, :wait, :tkwait, 
:eventloop_wait, :eventloop_tkwait, :eventloop_tkwait_visibility, :thread_wait, 
:thread_tkwait, :thread_tkwait_visibility, :wait_destroy, :wait_window, 
:eventloop_wait_destroy, :eventloop_wait_window, :thread_wait_destroy, 
:thread_wait_window, :tkwait_destroy, :tkwait_window, :eventloop_tkwait_destroy, 
:eventloop_tkwait_window, :thread_tkwait_destroy, :thread_tkwait_window, :bindtags, 
:bindtags=, :bindtags_shift, :bindtags_unshift, :busy_configinfo, :busy_current_configinfo, 
:busy_configure, :busy_cget, :busy, :busy_hold, :busy_forget, :busy_current?, :busy_status, 
:wm_aspect, :wm_attributes, :wm_client, :wm_colormapwindows, :wm_command, :wm_deiconify, 
:wm_focusmodel, :wm_forget, :wm_frame, :wm_geometry, :wm_grid, :wm_group, :wm_iconbitmap, 
:wm_iconphoto, :wm_iconphoto_default, :wm_iconify, :wm_iconmask, :wm_iconname, 
:wm_iconposition, :wm_iconwindow, :wm_manage, :wm_maxsize, :wm_minsize, 
:wm_overrideredirect, :wm_positionfrom, :wm_protocol, :wm_protocols, :wm_resizable, 
:wm_sizefrom, :wm_stackorder, :wm_stackorder_isabove, :wm_stackorder_is_above, 
:wm_stackorder_isbelow, :wm_stackorder_is_below, :wm_state, :wm_title, :wm_transient, 
:wm_withdraw, :winfo_atom, :winfo_atomname, :winfo_cells, :winfo_children, 
:winfo_classname, :winfo_class, :winfo_colormapfull, :winfo_containing, :winfo_depth, 
:winfo_exist?, :winfo_fpixels, :winfo_geometry, :winfo_height, :winfo_id, :winfo_interps, 
:winfo_mapped?, :winfo_manager, :winfo_appname, :winfo_parent, :winfo_widget, :winfo_pixels, 
:winfo_reqheight, :winfo_reqwidth, :winfo_rgb, :winfo_rootx, :winfo_rooty, :winfo_screen, 
:winfo_screencells, :winfo_screendepth, :winfo_screenheight, :winfo_screenmmheight, 
:winfo_screenmmwidth, :winfo_screenvisual, :winfo_screenwidth, :winfo_server, 
:winfo_toplevel, :winfo_visual, :winfo_visualid, :winfo_visualsavailable, 
:winfo_vrootheight, :winfo_vrootwidth, :winfo_vrootx, :winfo_vrooty, :winfo_width, 
:winfo_x, :winfo_y, :winfo_viewable, :winfo_pointerx, :winfo_pointery, :winfo_pointerxy, 
:path, :epath, :to_eval, :tk_send, :tk_send_without_enc, :tk_send_with_enc, 
:tk_send_to_list, :tk_send_to_list_without_enc, :tk_send_to_list_with_enc, 
:tk_send_to_simplelist, :tk_send_to_simplelist_without_enc, 
:tk_send_to_simplelist_with_enc, :method_missing, :event_generate, :bind, 
:bind_append, :bind_remove, :bindinfo, :config_hash_kv, :[], :[]=, :cget_tkstring, 
:cget, :cget_strict, :__check_available_configure_options, :configure, :configure_cmd, 
:configinfo, :current_configinfo, :font_configinfo, :fontobj, :font_configure, 
:latinfont_configure, :asciifont_configure, :kanjifont_configure, :font_copy, 
:latinfont_copy, :asciifont_copy, :Grid, :Pack, :Place, :root, :update, 
:callback_break, :callback_continue, :callback_return, :load_cmd_on_ip, 
:after, :after_idle, :after_cancel, :windowingsystem, :scaling, :scaling_displayof, 
:inactive, :inactive_displayof, :reset_inactive, :reset_inactive_displayof, :appname, 
:appsend_deny, :appsend, :rb_appsend, :appsend_displayof, :rb_appsend_displayof, :info, 
:mainloop, :mainloop_thread?, :mainloop_exist?, :is_mainloop?, :mainloop_watchdog, 
:do_one_event, :set_eventloop_tick, :get_eventloop_tick, :set_no_event_wait, 
:get_no_event_wait, :set_eventloop_weight, :get_eventloop_weight, :restart, 
:messageBox, :getOpenFile, :getMultipleOpenFile, :getSaveFile, :getMultipleSaveFile, 
:chooseColor, :chooseDirectory, :ip_eval, :ip_eval_without_enc, :ip_eval_with_enc, 
:ip_invoke, :ip_invoke_without_enc, :ip_invoke_with_enc, :tk_call, :tk_call_without_enc, 
:tk_call_with_enc, :_tk_call_to_list_core, :tk_call_to_list, :tk_call_to_list_without_enc, 
:tk_call_to_list_with_enc, :tk_call_to_simplelist, :tk_call_to_simplelist_without_enc, 
:tk_call_to_simplelist_with_enc, :subst, :install_cmd, :uninstall_cmd, :bind_all, 
:bind_append_all, :bind_remove_all, :bindinfo_all, :install_bind_for_event_class, 
:install_bind, :_symbolkey2str, :hash_kv, :_get_eval_string, :_get_eval_enc_str, 
:_conv_args]
忽略错误 do
  容器 = Agar容器.新建(300, 300)
  玩家 = Agar.新建('Shink')
  玩家2 = Agar.新建('Shink2')
  容器.添加(玩家)
  容器.添加(玩家2)
  容器.运行
  T测试框架.执行所有测试集
end
